package tests;// Generated by Selenium IDE

import model.DataContact;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import common.CommonFunctions;
import model.DataContact;


public class RemoveContactFromGroupTest extends TestBase {
  private WebDriver driver;

  @Test
  public void removeContactFromGroup() {
    app.allcontacts().openContactPage();
    if(app.allcontacts().getCount() == 0) {
      app.allcontacts().createContactshort(new DataContact().withFirstName("Alexander12"));
    }
    PickGroupForMethod();
    RemoveContactFromGroup();
    GoToHomePage();
  }

  private void GoToHomePage() {
    driver.findElement(By.linkText("home")).click();
  }

  private void RemoveContactFromGroup() {
    driver.findElement(By.name("remove")).click();
  }

  private void PickGroupForMethod() {
    driver.findElement(By.name("group")).click();
    {
      WebElement dropdown = driver.findElement(By.name("group"));
      dropdown.findElement(By.xpath("//option[. = 'SASHA']")).click();
    }
    driver.findElement(By.id("87")).click();
  }
}
